name: Run Workflow

on:
  workflow_run:
    workflows: ["Build Workflow"]
    types:
      - completed

jobs:
  run:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    # A침ade los pasos necesarios para ejecutar la aplicaci칩n.
    # Por ejemplo, si es una aplicaci칩n web, puedes usar un servidor local o un contenedor Docker.
 Por ejemplo, si es una aplicaci칩n web, puedes usar un servidor local o un contenedor Docker.
